name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest     # windows-latest   # mac-latest
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Initialize
        working-directory: packer
        run: |
          packer init  
        
      - name: Validate
        working-directory: packer
        run: |
          packer validate  

  deploy:
    runs-on: ubuntu-latest     # windows-latest   # mac-latest
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Initialize VPC
        working-directory: terraform/vpc
        run: |
          terraform init  